local HelixAC_CVarCode = {}

HelixAC_CVarCode['external'] = "ns_external"
HelixAC_CVarCode['require'] = "ns_require"

CreateConVar("external", HelixAC_CVarCode['external'], { FCVAR_CHEAT, FCVAR_PROTECTED, FCVAR_NOT_CONNECTED, FCVAR_USERINFO, FCVAR_UNREGISTERED, FCVAR_REPLICATED, FCVAR_UNLOGGED, FCVAR_DONTRECORD, FCVAR_SPONLY })
CreateConVar("require", HelixAC_CVarCode['require'], { FCVAR_CHEAT, FCVAR_PROTECTED, FCVAR_NOT_CONNECTED, FCVAR_USERINFO, FCVAR_UNREGISTERED, FCVAR_REPLICATED, FCVAR_UNLOGGED, FCVAR_DONTRECORD, FCVAR_SPONLY })